---
camera:
    learning_rate: 0.00001
    weight_decay: 0.1
left_eye:
    learning_rate: 0.00001
    weight_decay: 0.1
right_eye:
    learning_rate: 0.00001
    weight_decay: 0.1
ppo:
    learning_rate: 0.0005
    weight_decay: 0.001

imitation_coefficient: 0.9
batch_size: 64
image_size: 320
