---
camera:
    learning_rate: 0.0001
    weight_decay: 0.01
    alpha: 1
    beta: 1
    gamma: 1
left_eye:
    learning_rate: 0.0001
    weight_decay: 0.01
    alpha: 1
    beta: 1
    gamma: 1
right_eye:
    learning_rate: 0.0001
    weight_decay: 0.01
    alpha: 1
    beta: 1
    gamma: 1
ppo:
    learning_rate: 0.0005
    weight_decay: 0.001

imitation_coefficient: 0.9
batch_size: 64
image_size: 320
dataset_size: 10000
z_size: 256

model_name: 0.0001-0.95-0.01-l2loss-normalized_image-beta1
