---
camera:
    learning_rate: 0.0001
    decay_rate: 0.95
    decay_steps: 100
    weight_decay: 0.01
    alpha: -10
    beta: 1
    gamma: 1
left_eye:
    learning_rate: 0.0001
    decay_rate: 0.95
    decay_steps: 100
    weight_decay: 0.01
    alpha: -10
    beta: 1
    gamma: 1
right_eye:
    learning_rate: 0.0001
    decay_rate: 0.95
    decay_steps: 100
    weight_decay: 0.01
    alpha: -10
    beta: 1
    gamma: 1
ppo:
    learning_rate: 0.0005
    weight_decay: 0.001
    gamma: 0.9
    tau: 0.001
    noise_decay: 1.000005
    state_size: 128
    action_size: 10

imitation_coefficient: 0.9
batch_size: 32
image_size: 320
dataset_size: 10000
z_size: 128

model_name: DIM-0.0001-l2loss-normalized_image-z128-conv_avg_pool
