// Generated by gencpp from file candy/Step.msg
// DO NOT EDIT!


#ifndef CANDY_MESSAGE_STEP_H
#define CANDY_MESSAGE_STEP_H

#include <ros/service_traits.h>


#include <candy/StepRequest.h>
#include <candy/StepResponse.h>


namespace candy
{

struct Step
{

typedef StepRequest Request;
typedef StepResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Step
} // namespace candy


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::candy::Step > {
  static const char* value()
  {
    return "945e963769938e4ddc3288e80fdfddf4";
  }

  static const char* value(const ::candy::Step&) { return value(); }
};

template<>
struct DataType< ::candy::Step > {
  static const char* value()
  {
    return "candy/Step";
  }

  static const char* value(const ::candy::Step&) { return value(); }
};


// service_traits::MD5Sum< ::candy::StepRequest> should match 
// service_traits::MD5Sum< ::candy::Step > 
template<>
struct MD5Sum< ::candy::StepRequest>
{
  static const char* value()
  {
    return MD5Sum< ::candy::Step >::value();
  }
  static const char* value(const ::candy::StepRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::candy::StepRequest> should match 
// service_traits::DataType< ::candy::Step > 
template<>
struct DataType< ::candy::StepRequest>
{
  static const char* value()
  {
    return DataType< ::candy::Step >::value();
  }
  static const char* value(const ::candy::StepRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::candy::StepResponse> should match 
// service_traits::MD5Sum< ::candy::Step > 
template<>
struct MD5Sum< ::candy::StepResponse>
{
  static const char* value()
  {
    return MD5Sum< ::candy::Step >::value();
  }
  static const char* value(const ::candy::StepResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::candy::StepResponse> should match 
// service_traits::DataType< ::candy::Step > 
template<>
struct DataType< ::candy::StepResponse>
{
  static const char* value()
  {
    return DataType< ::candy::Step >::value();
  }
  static const char* value(const ::candy::StepResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CANDY_MESSAGE_STEP_H
