// Generated by gencpp from file candy/UpdateWeights.msg
// DO NOT EDIT!


#ifndef CANDY_MESSAGE_UPDATEWEIGHTS_H
#define CANDY_MESSAGE_UPDATEWEIGHTS_H

#include <ros/service_traits.h>


#include <candy/UpdateWeightsRequest.h>
#include <candy/UpdateWeightsResponse.h>


namespace candy
{

struct UpdateWeights
{

typedef UpdateWeightsRequest Request;
typedef UpdateWeightsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateWeights
} // namespace candy


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::candy::UpdateWeights > {
  static const char* value()
  {
    return "945e963769938e4ddc3288e80fdfddf4";
  }

  static const char* value(const ::candy::UpdateWeights&) { return value(); }
};

template<>
struct DataType< ::candy::UpdateWeights > {
  static const char* value()
  {
    return "candy/UpdateWeights";
  }

  static const char* value(const ::candy::UpdateWeights&) { return value(); }
};


// service_traits::MD5Sum< ::candy::UpdateWeightsRequest> should match 
// service_traits::MD5Sum< ::candy::UpdateWeights > 
template<>
struct MD5Sum< ::candy::UpdateWeightsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::candy::UpdateWeights >::value();
  }
  static const char* value(const ::candy::UpdateWeightsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::candy::UpdateWeightsRequest> should match 
// service_traits::DataType< ::candy::UpdateWeights > 
template<>
struct DataType< ::candy::UpdateWeightsRequest>
{
  static const char* value()
  {
    return DataType< ::candy::UpdateWeights >::value();
  }
  static const char* value(const ::candy::UpdateWeightsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::candy::UpdateWeightsResponse> should match 
// service_traits::MD5Sum< ::candy::UpdateWeights > 
template<>
struct MD5Sum< ::candy::UpdateWeightsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::candy::UpdateWeights >::value();
  }
  static const char* value(const ::candy::UpdateWeightsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::candy::UpdateWeightsResponse> should match 
// service_traits::DataType< ::candy::UpdateWeights > 
template<>
struct DataType< ::candy::UpdateWeightsResponse>
{
  static const char* value()
  {
    return DataType< ::candy::UpdateWeights >::value();
  }
  static const char* value(const ::candy::UpdateWeightsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CANDY_MESSAGE_UPDATEWEIGHTS_H
