// Generated by gencpp from file candy/ValueRequest.msg
// DO NOT EDIT!


#ifndef CANDY_MESSAGE_VALUEREQUEST_H
#define CANDY_MESSAGE_VALUEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace candy
{
template <class ContainerAllocator>
struct ValueRequest_
{
  typedef ValueRequest_<ContainerAllocator> Type;

  ValueRequest_()
    : a()  {
    }
  ValueRequest_(const ContainerAllocator& _alloc)
    : a(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::candy::ValueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::candy::ValueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ValueRequest_

typedef ::candy::ValueRequest_<std::allocator<void> > ValueRequest;

typedef boost::shared_ptr< ::candy::ValueRequest > ValueRequestPtr;
typedef boost::shared_ptr< ::candy::ValueRequest const> ValueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::candy::ValueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::candy::ValueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace candy

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::candy::ValueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::candy::ValueRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::candy::ValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::candy::ValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::candy::ValueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::candy::ValueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::candy::ValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cec2f53f86620c7bb01476cbe41b2fae";
  }

  static const char* value(const ::candy::ValueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcec2f53f86620c7bULL;
  static const uint64_t static_value2 = 0xb01476cbe41b2faeULL;
};

template<class ContainerAllocator>
struct DataType< ::candy::ValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "candy/ValueRequest";
  }

  static const char* value(const ::candy::ValueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::candy::ValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string a\n\
";
  }

  static const char* value(const ::candy::ValueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::candy::ValueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ValueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::candy::ValueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::candy::ValueRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CANDY_MESSAGE_VALUEREQUEST_H
