// Generated by gencpp from file candy/Value.msg
// DO NOT EDIT!


#ifndef CANDY_MESSAGE_VALUE_H
#define CANDY_MESSAGE_VALUE_H

#include <ros/service_traits.h>


#include <candy/ValueRequest.h>
#include <candy/ValueResponse.h>


namespace candy
{

struct Value
{

typedef ValueRequest Request;
typedef ValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Value
} // namespace candy


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::candy::Value > {
  static const char* value()
  {
    return "945e963769938e4ddc3288e80fdfddf4";
  }

  static const char* value(const ::candy::Value&) { return value(); }
};

template<>
struct DataType< ::candy::Value > {
  static const char* value()
  {
    return "candy/Value";
  }

  static const char* value(const ::candy::Value&) { return value(); }
};


// service_traits::MD5Sum< ::candy::ValueRequest> should match 
// service_traits::MD5Sum< ::candy::Value > 
template<>
struct MD5Sum< ::candy::ValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::candy::Value >::value();
  }
  static const char* value(const ::candy::ValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::candy::ValueRequest> should match 
// service_traits::DataType< ::candy::Value > 
template<>
struct DataType< ::candy::ValueRequest>
{
  static const char* value()
  {
    return DataType< ::candy::Value >::value();
  }
  static const char* value(const ::candy::ValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::candy::ValueResponse> should match 
// service_traits::MD5Sum< ::candy::Value > 
template<>
struct MD5Sum< ::candy::ValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::candy::Value >::value();
  }
  static const char* value(const ::candy::ValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::candy::ValueResponse> should match 
// service_traits::DataType< ::candy::Value > 
template<>
struct DataType< ::candy::ValueResponse>
{
  static const char* value()
  {
    return DataType< ::candy::Value >::value();
  }
  static const char* value(const ::candy::ValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CANDY_MESSAGE_VALUE_H
