(cl:defpackage candy-srv
  (:use )
  (:export
   "STEP"
   "<STEP-REQUEST>"
   "STEP-REQUEST"
   "<STEP-RESPONSE>"
   "STEP-RESPONSE"
   "UPDATEWEIGHTS"
   "<UPDATEWEIGHTS-REQUEST>"
   "UPDATEWEIGHTS-REQUEST"
   "<UPDATEWEIGHTS-RESPONSE>"
   "UPDATEWEIGHTS-RESPONSE"
   "VALUE"
   "<VALUE-REQUEST>"
   "VALUE-REQUEST"
   "<VALUE-RESPONSE>"
   "VALUE-RESPONSE"
  ))

